name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        with:
          path: docs/
        run: |
          python -m pip install --upgrade pip
          pip install -requirements.txt
      - name: Run tests with pytest
        with:
          path: tests/
        run: |
          pytest --exitfirst --verbose --failed-first \
          --cov=. --cov-report html